services:
  # api:
  #   build: .
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     - FLASK_DEBUG=1
  #     - PYTHONUNBUFFERED=1 
  #   depends_on:
  #     - db
  db:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
  pgadmin:
    image: dpage/pgadmin4:latest
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: user@localhost.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 8080:80